/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Data {
  export type ContentStruct = {
    title: string;
    url: string;
    submittedBy: AddressLike;
    likes: BigNumberish;
    tagIds: BigNumberish[];
  };

  export type ContentStructOutput = [
    title: string,
    url: string,
    submittedBy: string,
    likes: bigint,
    tagIds: bigint[]
  ] & {
    title: string;
    url: string;
    submittedBy: string;
    likes: bigint;
    tagIds: bigint[];
  };

  export type TagStruct = {
    name: string;
    createdBy: AddressLike;
    contentIds: BigNumberish[];
  };

  export type TagStructOutput = [
    name: string,
    createdBy: string,
    contentIds: bigint[]
  ] & { name: string; createdBy: string; contentIds: bigint[] };

  export type UserStruct = {
    userAddress: AddressLike;
    numberOfLikedContent: BigNumberish;
    submittedContent: BigNumberish[];
  };

  export type UserStructOutput = [
    userAddress: string,
    numberOfLikedContent: bigint,
    submittedContent: bigint[]
  ] & {
    userAddress: string;
    numberOfLikedContent: bigint;
    submittedContent: bigint[];
  };
}

export interface DataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllContent"
      | "getAllTags"
      | "getAllUsers"
      | "getContent"
      | "getContentByTag"
      | "getTag"
      | "getUser"
      | "getUserLikedContent"
      | "getUserSubmittedContent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllContent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTags",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getContent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getContentByTag",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getTag", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLikedContent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmittedContent",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllTags", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getContent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContentByTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTag", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserLikedContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmittedContent",
    data: BytesLike
  ): Result;
}

export interface Data extends BaseContract {
  connect(runner?: ContractRunner | null): Data;
  waitForDeployment(): Promise<this>;

  interface: DataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllContent: TypedContractMethod<[], [Data.ContentStructOutput[]], "view">;

  getAllTags: TypedContractMethod<[], [Data.TagStructOutput[]], "view">;

  getAllUsers: TypedContractMethod<[], [Data.UserStructOutput[]], "view">;

  getContent: TypedContractMethod<
    [url: string],
    [Data.ContentStructOutput],
    "view"
  >;

  getContentByTag: TypedContractMethod<
    [name: string],
    [Data.ContentStructOutput[]],
    "view"
  >;

  getTag: TypedContractMethod<[name: string], [Data.TagStructOutput], "view">;

  getUser: TypedContractMethod<
    [userAddress: AddressLike],
    [Data.UserStructOutput],
    "view"
  >;

  getUserLikedContent: TypedContractMethod<
    [userAddress: AddressLike],
    [Data.ContentStructOutput[]],
    "view"
  >;

  getUserSubmittedContent: TypedContractMethod<
    [userAddress: AddressLike],
    [Data.ContentStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllContent"
  ): TypedContractMethod<[], [Data.ContentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllTags"
  ): TypedContractMethod<[], [Data.TagStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllUsers"
  ): TypedContractMethod<[], [Data.UserStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getContent"
  ): TypedContractMethod<[url: string], [Data.ContentStructOutput], "view">;
  getFunction(
    nameOrSignature: "getContentByTag"
  ): TypedContractMethod<[name: string], [Data.ContentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTag"
  ): TypedContractMethod<[name: string], [Data.TagStructOutput], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [Data.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserLikedContent"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [Data.ContentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSubmittedContent"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [Data.ContentStructOutput[]],
    "view"
  >;

  filters: {};
}
