/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SlasherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "backendAddress"
      | "backendVault"
      | "rechargeVault"
      | "registerBackend"
      | "removeBackend"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "backendAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backendVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rechargeVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerBackend",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeBackend",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "backendAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rechargeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBackend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBackend",
    data: BytesLike
  ): Result;
}

export interface Slasher extends BaseContract {
  connect(runner?: ContractRunner | null): Slasher;
  waitForDeployment(): Promise<this>;

  interface: SlasherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backendAddress: TypedContractMethod<[], [string], "view">;

  backendVault: TypedContractMethod<[], [bigint], "view">;

  rechargeVault: TypedContractMethod<[], [void], "payable">;

  registerBackend: TypedContractMethod<[], [void], "payable">;

  removeBackend: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backendAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "backendVault"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rechargeVault"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "registerBackend"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "removeBackend"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
