/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortStrings__factory>;
    getContractFactory(
      name: "Channel4Contract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Channel4Contract__factory>;
    getContractFactory(
      name: "Create",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Create__factory>;
    getContractFactory(
      name: "Data",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Data__factory>;
    getContractFactory(
      name: "Interact",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Interact__factory>;
    getContractFactory(
      name: "Litigate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Litigate__factory>;
    getContractFactory(
      name: "Slasher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Slasher__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC5267",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "EIP712",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "ShortStrings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortStrings>;
    getContractAt(
      name: "Channel4Contract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Channel4Contract>;
    getContractAt(
      name: "Create",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Create>;
    getContractAt(
      name: "Data",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Data>;
    getContractAt(
      name: "Interact",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Interact>;
    getContractAt(
      name: "Litigate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Litigate>;
    getContractAt(
      name: "Slasher",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Slasher>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "Channel4Contract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Channel4Contract>;
    deployContract(
      name: "Create",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Create>;
    deployContract(
      name: "Data",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Data>;
    deployContract(
      name: "Interact",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Interact>;
    deployContract(
      name: "Litigate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Litigate>;
    deployContract(
      name: "Slasher",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Slasher>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC5267",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "EIP712",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "ShortStrings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "Channel4Contract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Channel4Contract>;
    deployContract(
      name: "Create",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Create>;
    deployContract(
      name: "Data",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Data>;
    deployContract(
      name: "Interact",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Interact>;
    deployContract(
      name: "Litigate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Litigate>;
    deployContract(
      name: "Slasher",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Slasher>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
